---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: ecs-task-execution-role
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Service": "ecs-tasks.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
  providerConfigRef:
    name: example
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: ecs-task-execution-rolepolicyattachment
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
    roleNameRef:
      name: ecs-task-execution-role
  providerConfigRef:
    name: example