apiVersion: batch.aws.crossplane.io/v1alpha1
kind: ComputeEnvironment
metadata:
  name: example-managed-ec2spot-computeenvironment
spec:
  forProvider:
    region: us-east-1
    type_: MANAGED
    ## Defined in examples/ec2
    subnetIdRefs:
      - name: sample-subnet1
    ## Defined in examples/batch
    securityGroupIdRefs:
      - name: batch-ce-sg
    ## Defined in examples/batch
    instanceRoleRef:
      name: ecsinstance-role-profile
    ## Defined in examples/batch
    spotIAMFleetRoleRef:
      name: spot-fleet-tagging-role
    tags:
      ce: "my-spotec2-ce"
    # for EC2 and EC2Spot: If the original allocation strategy is BEST_FIT,
    # infrastructure updates aren't supported.
    # In that case the only fields in computeResources that can be updated are:
    # minvCPUs and maxvCPUs
    computeResources:
      type_: SPOT
      allocationStrategy: SPOT_CAPACITY_OPTIMIZED # optional, AWS default is BEST_FIT
      minvCPUs: 1
      maxvCPUs: 24
      instanceTypes:
        - "optimal"
  providerConfigRef:
    name: example